// Code generated by MockGen. DO NOT EDIT.
// Source: toolprep.go
//
// Generated by this command:
//
//	mockgen -typed -source=toolprep.go -destination=mocks/toolprep_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	toolprep "claude-auto-permission/internal/llmclassifier/toolprep"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTool is a mock of Tool interface.
type MockTool struct {
	ctrl     *gomock.Controller
	recorder *MockToolMockRecorder
	isgomock struct{}
}

// MockToolMockRecorder is the mock recorder for MockTool.
type MockToolMockRecorder struct {
	mock *MockTool
}

// NewMockTool creates a new mock instance.
func NewMockTool(ctrl *gomock.Controller) *MockTool {
	mock := &MockTool{ctrl: ctrl}
	mock.recorder = &MockToolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTool) EXPECT() *MockToolMockRecorder {
	return m.recorder
}

// Sanitize mocks base method.
func (m *MockTool) Sanitize(in toolprep.Input) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sanitize", in)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sanitize indicates an expected call of Sanitize.
func (mr *MockToolMockRecorder) Sanitize(in any) *MockToolSanitizeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sanitize", reflect.TypeOf((*MockTool)(nil).Sanitize), in)
	return &MockToolSanitizeCall{Call: call}
}

// MockToolSanitizeCall wrap *gomock.Call
type MockToolSanitizeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockToolSanitizeCall) Return(arg0 json.RawMessage, arg1 error) *MockToolSanitizeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockToolSanitizeCall) Do(f func(toolprep.Input) (json.RawMessage, error)) *MockToolSanitizeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockToolSanitizeCall) DoAndReturn(f func(toolprep.Input) (json.RawMessage, error)) *MockToolSanitizeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Skippable mocks base method.
func (m *MockTool) Skippable(in toolprep.Input) (toolprep.Skippable, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Skippable", in)
	ret0, _ := ret[0].(toolprep.Skippable)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Skippable indicates an expected call of Skippable.
func (mr *MockToolMockRecorder) Skippable(in any) *MockToolSkippableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Skippable", reflect.TypeOf((*MockTool)(nil).Skippable), in)
	return &MockToolSkippableCall{Call: call}
}

// MockToolSkippableCall wrap *gomock.Call
type MockToolSkippableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockToolSkippableCall) Return(arg0 toolprep.Skippable, arg1 string) *MockToolSkippableCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockToolSkippableCall) Do(f func(toolprep.Input) (toolprep.Skippable, string)) *MockToolSkippableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockToolSkippableCall) DoAndReturn(f func(toolprep.Input) (toolprep.Skippable, string)) *MockToolSkippableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
