// Code generated by MockGen. DO NOT EDIT.
// Source: bedrock.go
//
// Generated by this command:
//
//	mockgen -typed -source=bedrock.go -destination=mocks/converser_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bedrockruntime "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
	gomock "go.uber.org/mock/gomock"
)

// Mockconverser is a mock of converser interface.
type Mockconverser struct {
	ctrl     *gomock.Controller
	recorder *MockconverserMockRecorder
	isgomock struct{}
}

// MockconverserMockRecorder is the mock recorder for Mockconverser.
type MockconverserMockRecorder struct {
	mock *Mockconverser
}

// NewMockconverser creates a new mock instance.
func NewMockconverser(ctrl *gomock.Controller) *Mockconverser {
	mock := &Mockconverser{ctrl: ctrl}
	mock.recorder = &MockconverserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockconverser) EXPECT() *MockconverserMockRecorder {
	return m.recorder
}

// Converse mocks base method.
func (m *Mockconverser) Converse(ctx context.Context, params *bedrockruntime.ConverseInput, optFns ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Converse", varargs...)
	ret0, _ := ret[0].(*bedrockruntime.ConverseOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Converse indicates an expected call of Converse.
func (mr *MockconverserMockRecorder) Converse(ctx, params any, optFns ...any) *MockconverserConverseCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Converse", reflect.TypeOf((*Mockconverser)(nil).Converse), varargs...)
	return &MockconverserConverseCall{Call: call}
}

// MockconverserConverseCall wrap *gomock.Call
type MockconverserConverseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockconverserConverseCall) Return(arg0 *bedrockruntime.ConverseOutput, arg1 error) *MockconverserConverseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockconverserConverseCall) Do(f func(context.Context, *bedrockruntime.ConverseInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error)) *MockconverserConverseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockconverserConverseCall) DoAndReturn(f func(context.Context, *bedrockruntime.ConverseInput, ...func(*bedrockruntime.Options)) (*bedrockruntime.ConverseOutput, error)) *MockconverserConverseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
