// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -typed -source=provider.go -destination=mocks/provider_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	providers "claude-auto-permission/internal/llmclassifier/providers"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Classify mocks base method.
func (m *MockProvider) Classify(ctx context.Context, req providers.Request) (providers.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classify", ctx, req)
	ret0, _ := ret[0].(providers.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Classify indicates an expected call of Classify.
func (mr *MockProviderMockRecorder) Classify(ctx, req any) *MockProviderClassifyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classify", reflect.TypeOf((*MockProvider)(nil).Classify), ctx, req)
	return &MockProviderClassifyCall{Call: call}
}

// MockProviderClassifyCall wrap *gomock.Call
type MockProviderClassifyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderClassifyCall) Return(arg0 providers.Result, arg1 error) *MockProviderClassifyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderClassifyCall) Do(f func(context.Context, providers.Request) (providers.Result, error)) *MockProviderClassifyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderClassifyCall) DoAndReturn(f func(context.Context, providers.Request) (providers.Result, error)) *MockProviderClassifyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Model mocks base method.
func (m *MockProvider) Model() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Model")
	ret0, _ := ret[0].(string)
	return ret0
}

// Model indicates an expected call of Model.
func (mr *MockProviderMockRecorder) Model() *MockProviderModelCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Model", reflect.TypeOf((*MockProvider)(nil).Model))
	return &MockProviderModelCall{Call: call}
}

// MockProviderModelCall wrap *gomock.Call
type MockProviderModelCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderModelCall) Return(arg0 string) *MockProviderModelCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderModelCall) Do(f func() string) *MockProviderModelCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderModelCall) DoAndReturn(f func() string) *MockProviderModelCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *MockProviderNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
	return &MockProviderNameCall{Call: call}
}

// MockProviderNameCall wrap *gomock.Call
type MockProviderNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderNameCall) Return(arg0 string) *MockProviderNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderNameCall) Do(f func() string) *MockProviderNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderNameCall) DoAndReturn(f func() string) *MockProviderNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
