// Code generated by MockGen. DO NOT EDIT.
// Source: classifier.go
//
// Generated by this command:
//
//	mockgen -typed -source=classifier.go -destination=mocks/classifier_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	toolprep "claude-auto-permission/internal/llmclassifier/toolprep"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockToolRegistry is a mock of ToolRegistry interface.
type MockToolRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockToolRegistryMockRecorder
	isgomock struct{}
}

// MockToolRegistryMockRecorder is the mock recorder for MockToolRegistry.
type MockToolRegistryMockRecorder struct {
	mock *MockToolRegistry
}

// NewMockToolRegistry creates a new mock instance.
func NewMockToolRegistry(ctrl *gomock.Controller) *MockToolRegistry {
	mock := &MockToolRegistry{ctrl: ctrl}
	mock.recorder = &MockToolRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRegistry) EXPECT() *MockToolRegistryMockRecorder {
	return m.recorder
}

// Tool mocks base method.
func (m *MockToolRegistry) Tool(toolName string) toolprep.Tool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tool", toolName)
	ret0, _ := ret[0].(toolprep.Tool)
	return ret0
}

// Tool indicates an expected call of Tool.
func (mr *MockToolRegistryMockRecorder) Tool(toolName any) *MockToolRegistryToolCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tool", reflect.TypeOf((*MockToolRegistry)(nil).Tool), toolName)
	return &MockToolRegistryToolCall{Call: call}
}

// MockToolRegistryToolCall wrap *gomock.Call
type MockToolRegistryToolCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockToolRegistryToolCall) Return(arg0 toolprep.Tool) *MockToolRegistryToolCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockToolRegistryToolCall) Do(f func(string) toolprep.Tool) *MockToolRegistryToolCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockToolRegistryToolCall) DoAndReturn(f func(string) toolprep.Tool) *MockToolRegistryToolCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
